### ISSUE TITLE
Wiki: gyroscope and position

### ISSUE THREAD

**Issue by koldolrobotikas** [sanjayseshan/spikeprime-vscode#1]
This is about 
hub.motion.gyroscope() --> tuple with (x,y,z) axis in degrees
hub.motion.position() --> tuple with (x,y,z) axis in degrees --> seems similar to gyroscope but not the same values?

I have been doing some test using Putty. Those are my conclusions:
*hub.motion.gyroscope() -- > (x,y,z) axis in degrees/s
*hub.motion.position() -- > (yaw,pitch,roll) in degrees (those values seem to be internally calculated)

for the last one, it is possible to reset the jaw value:
*hub.motion.reset_jaw() : it resets the yaw value

or set the value you want, for instance
*hub.motion.preset_jaw(45) : so, the jaw value will be 45º

**Comment by sanjayseshan** [comment]
Thank you. I will add these. I assume you mean "yaw" and not "jaw"?

**Comment by koldolrobotikas** [comment]
Yaw, yes, of course.
