### ISSUE TITLE
hub.battery notes

### ISSUE THREAD

**Issue by smr99** [sanjayseshan/spikeprime-vscode#10]
Couple quick notes about the hub.battery section.  First: yes the output of info() is a json string, so the question mark can be removed.

Second: at least one of the fields in that info can be obtained directly.  I didn't check any others, but hub.battery.capacity_left() will return the battery capacity.  Tested this on my mindstorms 51515 kit.

Cheers!  Thanks for the tips.

**Comment by sanjayseshan** [comment]
Thank you! I will update the docs.

**Comment by sanjayseshan** [comment]
I assume hub.battery.capacity_left() returns a float?

**Comment by smr99** [comment]
Good question.  I've only ever received 100, so I don't know.  Might be integer.

On January 3, 2021 10:17:10 a.m. CST, Sanjay Seshan <notifications@github.com> wrote:
>I assume hub.battery.capacity_left() returns a float?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sanjayseshan/spikeprime-vscode/issues/10#issuecomment-753640431

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sanjayseshan** [comment]
I see. It is a percentage....I had assumed it was voltage. I have updated the docs to match.
