### ISSUE TITLE
Unable to Run Template Program.

### ISSUE THREAD

**Issue by JoeGemperline** [sanjayseshan/spikeprime-vscode#5]
Getting an error when attempting to "Start Spike Prime Program". It does not run when selected on hub ether. Thanks so much for building this extension. I see a real need for this. I'm working on Window 10 with Python 3.7.4. Thanks!

PS C:\Users\Name\Desktop\SpikePrime> python C:\spiketools\spikejsonrpc.py -t COM7 upload "c:\Users\Name\Desktop\SpikePrime\SpikeTest.py" 0
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 519/519 [00:00<00:00, 853B/s]
PS C:\Users\Name\Desktop\SpikePrime> python C:\spiketools\spikejsonrpc.py -t COM7 start 0 && python C:\spiketools\\readserial.py COM7
At line:1 char:54
+ python C:\spiketools\spikejsonrpc.py -t COM7 start 0 && python C:\spi ...
+                                                      ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

**Comment by jeffdamp-wave** [comment]
yes looks like the extension is adding some stuff that isn't needed for this command.  Fortunately you can just run this command from the terminal window and it will work 
python C:\spiketools\spikejsonrpc.py -t COM7 start 0

**Comment by sanjayseshan** [comment]
Turns out that this command syntax only works in Command Prompt. I didn't realize that it didn't work in Powershell (which is what it looks like you are using) since my default console in vs code is set to Command Prompt. The readserial.py command is used to read the print messages via the serial port to the PC console. It is not needed, so you can do what @jeffdamp-wave suggested. However, if you want the command to work as is, you would have to switch the default console to use cmd.exe (see https://stackoverflow.com/questions/44435697/vscode-change-default-terminal). I updated the wiki to reflect this.

**Comment by JoeGemperline** [comment]
After setting default to Command Prompt I still get this error in VC. When running from the command prompt it seems to run but I expected blinking lights and that is not what happens. When run from terminal or the hub it locks up and a restart is required. Thanks for the quick responses and thanks for this effort.

**Comment by sanjayseshan** [comment]
Hmmm. Not sure what is happening. The hub does sometimes lock up when starting the program from a PC because the serial reader doesn't always close correctly. Perhaps try the new SPIKE api (https://github.com/sanjayseshan/spikeprime-vscode/wiki/SPIKE-API).

**Comment by JoeGemperline** [comment]
Progress! I could run the Spike API from the Terminal. I get the same error in Visual Code. If you have a recommendation to try and fix the Visual Code command I would love to try it.

**Comment by jeffdamp-wave** [comment]
the .vsix file is really just a zip file so if there isn't something you don't like you can extract the extension.js and modify it.  I added some code to copy in a spike.py file into any new project.  I took all of the help documentation and stubbed out the function so the students would have useful intellisense right in VSCode.

**Comment by sanjayseshan** [comment]
V0.0.3 (https://github.com/sanjayseshan/spikeprime-vscode/releases/tag/v0.0.3) does not include the && in the command  as it was before the serial reader was added. I'm not sure why it does not work for you. The command works correctly on my computer which is set use use Command Prompt. Perhaps the extension does not recognize the switch to cmd.exe correctly? Try https://blog.jongallant.com/2017/02/vs-code-integrated-terminal-powershell-default-change-to-cmd/ and restart VS Code.

**Comment by JoeGemperline** [comment]
The Visual Studio Code restart did the trick. I can now run the Spike Prime API from Visual code using your extension. I did not have luck with the Hub API template, but I'm OK without it for now. Thanks for the help!!

Thanks
Joe
